### Register
POST http://localhost:9999/auth/register
Content-Type: application/json
Accept-Language: en

{
  "username": "gofurovmuhammadsolih004@gmail.com",
  "name": "Salome",
  "password": "secret"
}

### Login
POST http://localhost:9999/auth/login
Content-Type: application/json

{
  "username": "gofurovmuhammadsolih004@gmail.com",
  "password": "secret"
}